In [8]:
import numpy as np

## EM-algorithm

In [9]:
E = ...


def e_step():
    return ...

def m_step():
    return ...

while ():
    pass

In [10]:
p = np.zeros((2, 2, 3))
print(p)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [11]:
# initialize
imax = 50

F = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 1], [0, 5, 0]])
T = np.array([[1, 2, 0, 2, 0], [0, 3, 4, 0, 0], [5, 6, 0, 0, 7]])
G = F.dot(T)
print(len(F))
print(T.shape[1])
print(len(T))

# E
# http://www.machinelearning.ru/wiki/images/7/7c/Voron-2014-06-27-school-VI.pdf
def E_step(F,T):
    nd = np.zeros(5); nt = np.zeros(3); nwt = np.zeros((4,3)); ntd = np.zeros((3,5))
    ptwd = np.zeros((4, 5 ,3))
    for w in range(0, len(F)):
        for d in range(0, T.shape[1]):
            z = F[w,:].dot(T[:,d])
            print(F[w,:], T[:,d], w, d, z)
            for j in range(0, len(T)):
                ptwd[w,d,j] = 0 if z==0 else F[w,t]*T[j,t]/z
    print(ptwd)

# M
def M_step(ptwd):
    nwt = np.zeros((len(F), len(T)))
    for w in range(0, len(F)):
        for t in range(0, F.shape[1]):
            for d in range(0, T.shape[1]):
                nwt[w,t] += ptwd[w, d, t]*G[w,d]
            print(nwt)
    for w in range(0, len(F)):
        for t in range(0, F.shape[1]):
            F[w,t] = nwt[w,t]/(sum(nwt[w,:]))
                          
    ntd = np.zeros((T.shape[0], T.shape[1]))
    for d in range(0, T.shape[1]):
        for t in range(0, F.shape[1]):
            for w in range(0, len(F)):
                ntd[t,d] += ptwd[w, d, t]*G[w,d]
            print(nwt)
    for t in range(0, len(T)):
        for d in range(0, T.shape[1]):
            T[t,d] = ntd[t,d]/(sum(ntd[t,:]))
                          
    return F,T        


4
5
3


In [12]:
for i in range(0, imax):
    temp = EMalg(temp)

NameError: name 'EMalg' is not defined

## SVD

In [13]:
import numpy as np

M = np.random.normal(size = (4, 3))
B = np.random.normal(size = (4, 5))
print(M, B)

[[-0.59287234 -0.15382084 -1.50184995]
 [ 0.28860075 -0.4947321  -0.56265758]
 [-0.64559097  0.03620702 -0.51709442]
 [ 1.62590596  0.33378219 -1.28697403]] [[ 1.70602718  2.78058122 -1.16741243 -0.51482179  1.32119812]
 [-0.52900785 -0.30705362  1.94949521 -0.86390818  0.33349044]
 [ 1.27616049  1.11530259 -0.53087143 -0.19103899  1.14928696]
 [-0.10304308 -0.29489732 -0.21734192 -0.55959304 -0.25594667]]


In [14]:
# X = np.dot(np.linalg.inv(M), B)
# X = np.linalg.solve(M, B)
# print(X)


In [15]:
M = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 1], [0, 5, 0]])
X = np.array([[1, 2, 0, 2, 0], [0, 3, 4, 0, 0], [5, 6, 0, 0, 7]])
B = M.dot(X)
print(M)
print(X)
print(M.dot(X))

[[1 2 3]
 [4 5 6]
 [0 0 1]
 [0 5 0]]
[[1 2 0 2 0]
 [0 3 4 0 0]
 [5 6 0 0 7]]
[[16 26  8  2 21]
 [34 59 20  8 42]
 [ 5  6  0  0  7]
 [ 0 15 20  0  0]]


In [18]:
 U, s, Vt = np.linalg.svd(M, full_matrices=True)
print(U.shape, Vt.shape, s.shape)

(4, 4) (3, 3) (3,)


In [19]:
S = np.zeros((4, 3))
S[:3, :3] = np.diag(s)
print(S)


[[ 10.02290673   0.           0.        ]
 [  0.           3.96172745   0.        ]
 [  0.           0.           0.91981319]
 [  0.           0.           0.        ]]


### Проверки

In [20]:
print( np.allclose(M, np.dot(U, np.dot(S, Vt))) )
print( np.dot(np.transpose(U), U) )
print( S.transpose().dot(S) )

True
[[  1.00000000e+00  -8.32667268e-17   2.22044605e-16   8.32667268e-17]
 [ -8.32667268e-17   1.00000000e+00  -1.94289029e-16  -4.16333634e-17]
 [  2.22044605e-16  -1.94289029e-16   1.00000000e+00   9.02056208e-17]
 [  8.32667268e-17  -4.16333634e-17   9.02056208e-17   1.00000000e+00]]
[[ 100.45865935    0.            0.        ]
 [   0.           15.69528435    0.        ]
 [   0.            0.            0.8460563 ]]


In [23]:
from scipy import linalg
temp = np.dot( linalg.inv(S.transpose().dot(S)), np.transpose(S) ).dot(U.transpose())
X1 = np.dot(np.dot(Vt.transpose(), temp) ,B)
print(X1)

[[  1.00000000e+00   2.00000000e+00  -8.88178420e-16   2.00000000e+00
   -3.55271368e-15]
 [  5.27355937e-16   3.00000000e+00   4.00000000e+00  -1.38777878e-17
    7.49400542e-16]
 [  5.00000000e+00   6.00000000e+00   2.66453526e-15   1.11022302e-16
    7.00000000e+00]]


In [24]:
print( np.allclose(X1, X) )

True
