In [1]:
import numpy as np
import pandas as pd

# Read matrix

In [8]:
M = pd.read_csv('../../analysis/M.csv', index_col='motifs')
M = M.values
M

array([[  6.57604082,   6.86500202,   7.13575951, ...,   8.72667739,
         11.10949625,   6.74301493],
       [  6.8204945 ,   4.98351181,   7.70167858, ...,   5.22749207,
          6.02740839,   6.52961262],
       [  7.06839643,   5.59367278,   7.96232512, ...,   5.58347746,
         10.13682404,   6.5949579 ],
       ..., 
       [  6.62600897,   6.23942651,   6.48791657, ...,   7.6230222 ,
          5.24075466,   7.31636566],
       [  6.02704631,   7.58048362,   6.64826626, ...,   8.1129282 ,
          5.24075466,   7.31636566],
       [  8.11138742,   5.59995929,   9.69581248, ...,   8.8030464 ,
          9.59363602,   7.66925855]])

In [11]:
E = pd.read_csv('../../analysis/E.csv', header=None, index_col=0)
E = E.values
E

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.36282755,   0.33896971, ...,   0.66575677,
          1.61019035,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ..., 
       [  0.17599736,   0.        ,   0.        , ...,   1.33151355,
          1.20764276,   0.32056849],
       [  0.70398946,   0.7256551 ,   0.67793942, ...,   0.        ,
          0.60382138,   0.64113698],
       [ 23.58364689,  26.30499739,  27.96500094, ...,  19.97270323,
         19.72483177,  14.74615065]])

In [24]:
A = pd.read_csv('../../analysis/A.csv', header=None, index_col=0).values
A

array([[ 10.20784716,   8.52644743,  13.21981862, ...,   0.        ,
          6.44076139,  19.87524652],
       [  7.57063086,   7.68398308,   6.38152754, ...,  26.97075328,
         16.36311271,   0.64113698],
       [ 18.83171804,  13.42461936,  14.57569746, ...,   0.        ,
          0.20127379,   0.        ],
       ..., 
       [  0.52799209,   0.36282755,   0.50845456, ...,   0.        ,
          0.        ,   0.        ],
       [  1.75997365,   1.08848265,   1.01690912, ...,   0.        ,
          0.        ,   0.        ],
       [ 14.84335916,  16.42515109,  17.93594608, ...,  34.37161068,
         38.61517682,  36.86537661]])

# Algorithm

### EM-algorithm

In [12]:
E = ...


def e_step():
    return ...

def m_step():
    return ...

while ():
    pass

In [13]:
p = np.zeros((2, 2, 3))
print(p)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [11]:
# initialize
imax = 50

F = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 1], [0, 5, 0]])
T = np.array([[1, 2, 0, 2, 0], [0, 3, 4, 0, 0], [5, 6, 0, 0, 7]])
G = F.dot(T)
print(len(F))
print(T.shape[1])
print(len(T))

# E
# http://www.machinelearning.ru/wiki/images/7/7c/Voron-2014-06-27-school-VI.pdf
def E_step(F,T):
    nd = np.zeros(5); nt = np.zeros(3); nwt = np.zeros((4,3)); ntd = np.zeros((3,5))
    ptwd = np.zeros((4, 5 ,3))
    for w in range(0, len(F)):
        for d in range(0, T.shape[1]):
            z = F[w,:].dot(T[:,d])
            print(F[w,:], T[:,d], w, d, z)
            for j in range(0, len(T)):
                ptwd[w,d,j] = 0 if z==0 else F[w,t]*T[j,t]/z
    print(ptwd)

# M
def M_step(ptwd):
    nwt = np.zeros((len(F), len(T)))
    for w in range(0, len(F)):
        for t in range(0, F.shape[1]):
            for d in range(0, T.shape[1]):
                nwt[w,t] += ptwd[w, d, t]*G[w,d]
            print(nwt)
    for w in range(0, len(F)):
        for t in range(0, F.shape[1]):
            F[w,t] = nwt[w,t]/(sum(nwt[w,:]))
                          
    ntd = np.zeros((T.shape[0], T.shape[1]))
    for d in range(0, T.shape[1]):
        for t in range(0, F.shape[1]):
            for w in range(0, len(F)):
                ntd[t,d] += ptwd[w, d, t]*G[w,d]
            print(nwt)
    for t in range(0, len(T)):
        for d in range(0, T.shape[1]):
            T[t,d] = ntd[t,d]/(sum(ntd[t,:]))
                          
    return F,T        


4
5
3


In [12]:
for i in range(0, imax):
    temp = EMalg(temp)

NameError: name 'EMalg' is not defined

### SVD

Тестовые значения матриц

In [15]:
# X = np.dot(np.linalg.inv(M), B)
# X = np.linalg.solve(M, B)
# print(X)


In [16]:
M = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 1], [0, 5, 0]])
X = np.array([[1, 2, 0, 2, 0], [0, 3, 4, 0, 0], [5, 6, 0, 0, 7]])
B = M.dot(X)
print(M)
print(X)
print(M.dot(X))

[[1 2 3]
 [4 5 6]
 [0 0 1]
 [0 5 0]]
[[1 2 0 2 0]
 [0 3 4 0 0]
 [5 6 0 0 7]]
[[16 26  8  2 21]
 [34 59 20  8 42]
 [ 5  6  0  0  7]
 [ 0 15 20  0  0]]


In [17]:
 U, s, Vt = np.linalg.svd(M, full_matrices=True)
print(U.shape, Vt.shape, s.shape)

(4, 4) (3, 3) (3,)


### Проверки

In [19]:
print( np.allclose(M, np.dot(U, np.dot(S, Vt))) )
print( np.dot(np.transpose(U), U) )
print( S.transpose().dot(S) )

True
[[  1.00000000e+00  -8.32667268e-17   2.22044605e-16   8.32667268e-17]
 [ -8.32667268e-17   1.00000000e+00  -1.94289029e-16  -4.16333634e-17]
 [  2.22044605e-16  -1.94289029e-16   1.00000000e+00   9.02056208e-17]
 [  8.32667268e-17  -4.16333634e-17   9.02056208e-17   1.00000000e+00]]
[[ 100.45865935    0.            0.        ]
 [   0.           15.69528435    0.        ]
 [   0.            0.            0.8460563 ]]


In [20]:
from scipy import linalg
temp = np.dot( linalg.inv(S.transpose().dot(S)), np.transpose(S) ).dot(U.transpose())
X1 = np.dot(np.dot(Vt.transpose(), temp) ,B)
print(X1)

[[  1.00000000e+00   2.00000000e+00  -8.88178420e-16   2.00000000e+00
   -3.55271368e-15]
 [  5.27355937e-16   3.00000000e+00   4.00000000e+00  -1.38777878e-17
    7.49400542e-16]
 [  5.00000000e+00   6.00000000e+00   2.66453526e-15   1.11022302e-16
    7.00000000e+00]]


In [21]:
print( np.allclose(X1, X) )

True
